project:
  type: website
  output-dir: docs
execute-dir: project
format:
  html:
    toc: true
    theme: cosmo
    embed-resources: true
    code-fold: true
    code-summary: "Show code"
    number-sections: true
    fig-cap-location: bottom
execute:
  freeze: auto
  echo: true
